### ISSUE TITLE
Use hostnames instead of modes

### ISSUE THREAD

**Issue by guineawheek** [gragas/simpletcp#1]
What's wrong with hostnames? Sometimes you do need to bind to IPs other than localhost or the wildcard address, such as if you want a service accessible on a private network, and not the public Internet. 

Besides, this functionality is usually what people expect when they use networking libraries, in or out of the standard Python modules or in network programming in general, and if you really want the wildcard address, simply passing a blank string to bind() will do the trick.

**Comment by gragas** [comment]
This is a good point. Honestly, I'm quite a novice when it comes to networking. If you think this is a good idea, by all means, fork this and make a pull request.

If you don't have time or don't want to contribute for whatever reason, I think you described the idea well enough for me to implement it on my own.

**Comment by guineawheek** [comment]
I was about to make a pull request, but you seem to have solved the issue on your own very well.

Good luck to your project.

**Comment by gragas** [comment]
Thank you for the feedback.
